logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR

server:
  port: 8081
  servlet:
    context-path: /msBase
---
keycloak:
  enabled: true
  bearer-only: true
  auth-server-url: http://localhost:8080
  resource: base-ws-server
  realm: base-technicla-test
  public-client: true
  principal-attribute: preferred_username
  credentials:
   secret: Be147dluflQ7NecUl3pbWq1OOsRthl8D
  use-resource-role-mappings: false
  allowAnyHostname: true
  ssl-required: external
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: j-0980161816
    hikari:
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      connectionTestQuery: SELECT 1

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect